<?php
$categories_model = $this->getModel('categories');
$category = $categories_model->getOneById($this->element_id);
?>
<?php include_once('elements/header.phtml');?>
<div class="container-fluid">
    <div class="row content">
        <?php include_once('elements/menu.phtml');?>
        <div class="col-sm-10">
            <h1>
                <small><?php echo $this->getPageLabel();?></small>
            </h1>
            <hr>
            <form action="?action=category_list" method="post">
                <input type="hidden" name="model" value="categories"/>
                <input type="hidden" name="id" value="<?php if($this->action == 'edit_category') echo $category->getId();?>"/>
                <div class="col-sm-10">
                    <div class="form-group">
                        <label for="category">Kategoria</label>
                        <input type="text" class="form-control" name="category" id="category" placeholder="Wprowadź Kategorię" required value="<?php if(!empty($category)) echo $category->getCategory();?>"/>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary float-right">Zapisz</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<?php include_once('elements/footer.phtml');?>