<?php
$products_model = $this->getModel('products');
$product = $products_model->getOneById($this->element_id);
$categories_model = $this->getModel('categories');
?>
<?php include_once('elements/header.phtml');?>
<div class="container-fluid">
    <div class="row content">
        <?php include_once('elements/menu.phtml');?>
        <div class="col-sm-10">
            <h1>
                <small><?php echo $this->getPageLabel();?></small>
            </h1>
            <hr>
            <form action="?action=product_list" method="post">
                <input type="hidden" name="model" value="products"/>
                <input type="hidden" name="id" value="<?php if($this->action == 'edit_product') echo $product->getId();?>"/>
                <div class="col-sm-10">
                    <div class="form-group">
                        <label for="name">Nazwa Produktu</label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="Wprowadź nazwę produkru" required value="<?php if(!empty($product)) echo $product->getName();?>"/>
                    </div>
                    <div class="form-group">
                        <label for="quantity">Ilość</label>
                        <input type="text" class="form-control" name="quantity" id="quantity" placeholder="Wprowadź ilość" required value="<?php if(!empty($product)) echo $product->getQuantity();?>"/>
                    </div>
                    <div class="form-group">
                        <label for="category">Kategoria</label>
                        <select class="form-control" name="category" id="category">
                            <?php if($this->action == 'edit_product'):?>
                            <option value="<?php if(!empty($product)) echo $product->getCategory();?>"><?php if(!empty($product)) echo $product->getCategory();?></option>
                            <?php else:?>
                            <option value="" disabled selected>Wybierz Kategorię</option>
                            <?php endif;?>
                            <?php foreach($categories_model->getAllClass() as $category):?>
                            <option value="<?php echo $category->getCategory();?>"><?php echo $category->getCategory();?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary float-right">Zapisz</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<?php include_once('elements/footer.phtml');?>