<?php
$clients_model = $this->getModel('clients');
$client = $clients_model->getOneById($this->element_id);
?>
<?php include_once ('elements/header.phtml');?>
<div class="container-fluid">
    <div class="row content">
        <?php include_once ('elements/menu.phtml')?>
        <div class="col-sm-10">
            <h1>
                <small><?php echo $this->getPageLabel();?></small>
            </h1>
            <hr>
            <form action="?action=client_list" method="post">
                <input type="hidden" name="model" value="clients"/>
                <input type="hidden" name="id" value="<?php if($this->action == 'edit_client') echo $client->getId();?>"/>
                <div class="col-sm-10">
                    <div class="form-group">
                        <label for="firstname">Imie</label>
                        <input type="text" class="form-control" name="firstname" id="firstname" placeholder="Wprowadź imie" required value="<?php if(!empty($client)) echo $client->getFirstname();?>"/>
                    </div>
                    <div class="form-group">
                        <label for="lastname">Nazwisko</label>
                        <input type="text" class="form-control" name="lastname" id="lastname" placeholder="Wprowadź nazwisko" required value="<?php if(!empty($client)) echo $client->getLastname();?>"/>
                    </div>
                    <div class="form-group">
                        <label for="phone">Numer Telefonu</label>
                        <input type="text" class="form-control" name="phone" id="phone" placeholder="Wprowadź numer telefonu" required value="<?php if(!empty($client)) echo $client->getPhone();?>"/>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary float-right">Zapisz</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<?php include_once('elements/footer.phtml');?>