<?php
$categories_model = $this->getModel('categories');
$categories = $categories_model->getAll();
?>
<?php include_once('elements/header.phtml');?>
<div class="container-fluid">
    <div class="row content">
        <?php include_once('elements/menu.phtml');?>
        <div class="col-sm-10">
            <h1>
                <small><?php echo $this->getPageLabel() . '(' . count($categories) . ')';?></small>
            </h1>
            <div class="up-button">
                <a href="?action=add_category" data-toggle="tooltip" title="Dodaj Kategorię" data-placement="left">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>
                </a>
            </div>
            <hr>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Kategorie</th>
                        <th>Akcje</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($categories as $nr=>$category):?>
                    <tr>
                        <th scope="row"><?php echo $nr+1;?></th>
                        <td><?php echo $category->getCategory();?></td>
                        <td>
                            <a href="?action=edit_category&id=<?php echo $category->getId();?>" data-toggle="tooltip" title="Edytuj" data-placement="left">
                                <button type="button" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </button>
                            </a>
                            <a href="?action=delete_category&id=<?php echo $category->getId();?>" data-toggle="tooltip" title="Usuń" data-placement="right">
                                <button type="button" class="btn btn-danger">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </a>
                        </td>
                    </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php include_once('elements/footer.phtml');