<?php
$categories_model = $this->getModel('categories');
$categories = $categories_model->getAllAssoc();
?>
<?php include_once('elements/header.phtml');?>
<div class="container-fluid">
    <div class="row content">
        <?php include_once('elements/menu.phtml');?>
        <div class="col-sm-10">
            <h1>
                <small><?php echo $this->getPageLabel() . '(' . count($categories) . ')';?></small>
            </h1>
            <div class="up-button">
                <a href="?action=add_category" data-toggle="tooltip" title="Dodaj Kategorię" data-placement="left">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>
                </a>
            </div>
            <hr>
            
            <div ng-app="categoryApp" ng-controller="categoryController">
                <div class="form-group">
                    <div class="col-sm-2">
                        <input type="text" class="form-control" ng-model="searchCategory" placeholder="Szukaj kategorii...">
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th ng-click="orderByMe('category')" title="Sortuj kategorię">Kategorie</th>
                            <th>Akcje</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr ng-repeat="x in category_list | filter: {category: searchCategory} | orderBy: categoryOrderBy">
                            <th>{{$index+1}}</th>
                            <td>{{x.category}}</td>
                            <td>
                                <a href="?action=edit_category&id={{x.id}}" data-toggle="tooltip" title="Edytuj" data-placement="left">
                                    <button type="button" class="btn btn-primary">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </button>
                                </a>
                                <a href="?action=delete_category&id={{x.id}}" data-toggle="tooltip" title="Usuń" data-placement="right">
                                    <button type="button" class="btn btn-danger">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <script>
                var app = angular.module("categoryApp", []);
                app.controller("categoryController", function($scope){
                    $scope.category_list = <?php echo json_encode($categories);?>;
                    $scope.orderByMe = function(x){
                        $scope.categoryOrderBy = x;
                    }
                });
            </script>
        </div>
    </div>
</div>
<?php include_once('elements/footer.phtml');