<?php
$products_model = $this->getModel('products');
$categories_model = $this->getModel('categories');
if($this->category_name == 'all' || empty($this->category_name)){
    $products = $products_model->getAll();
}else{
    $products = $products_model->getAllWithExactCategory($this->category_name);
}
?>
<?php include_once('elements/header.phtml');?>
<div class="container-fluid">
    <div class="row content">
        <?php include_once('elements/menu.phtml');?>
        <div class="col-sm-10">
            <h1>
                <small>
                <?php 
                if($this->category_name == 'all' || empty($this->category_name)){
                    echo $this->getPageLabel() . '(Wszystkie)' . '(' . count($products) . ')';
                }else{
                    echo $this->getPageLabel() . '(' . ucfirst($this->category_name) . ')' . '(' . count($products) . ')';
                }
                ?>
                </small>
            </h1>
            <div class="up-button">
                <a href="?action=add_product" data-toggle="tooltip" title="Dodaj Produkt" data-placement="left">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>
                </a>
            </div>
            <hr>
            <div class="btn-group">
                <button type="button" class="btn btn-primary btn-lg dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Kategorie</button>
                <div class="dropdown-menu">
                    <li class="dropdown"><a class="dropdown-item" href="?action=product_list&category_name=all">Wszystkie</a></li>
                    <?php foreach($categories_model->getAll() as $category):?>
                    <li class="dropdown"><a class="dropdown-item" href="?action=product_list&category_name=<?php echo $category->getCategory();?>"><?php echo $category->getCategory();?></a></li>
                    <div class="dropdown-divider"></div>
                    <?php endforeach;?>
                </div>
            </div>
            <hr>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nazwa Produktu</th>
                        <th>Ilość</th>
                        <th>Kategoria</th>
                        <th>Akcje</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($products as $nr=>$product):?>
                    <tr>
                        <th scope="row"><?php echo $nr+1;?></th>
                        <td><?php echo $product->getName();?></td>
                        <td><?php echo $product->getQuantity();?></td>
                        <td><?php echo $product->getCategory();?></td>
                        <td>
                            <a href="?action=edit_product&id=<?php echo $product->getId();?>" data-toggle="tooltip" title="Edytuj" data-placement="left">
                                <button type="button" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </button>
                            </a>
                            <a href="?action=delete_product&id=<?php echo $product->getId();?>" data-toggle="tooltip" title="Usuń" data-placement="right">
                                <button type="button" class="btn btn-danger">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </a>
                        </td>
                    </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php include_once('elements/footer.phtml');?>