<?php
$visits_model = $this->getModel('visits');
$visits = $visits_model->getAll();
?>
<?php include_once('elements/header.phtml');?>
<div class="container-fluid">
    <div class="row content">
        <?php include_once('elements/menu.phtml');?>
        <div class="col-sm-10">
            <h1>
                <small><?php echo $this->getPageLabel() . '(' . count($visits) . ')';?></small>
            </h1>
            <div class="up-button">
                <a href="?action=add_visit" data-toggle="tooltip" title="Dodaj Wizytę" data-placement="left">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>
                </a>
            </div>
            <hr>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Imie</th>
                        <th>Nazwisko</th>
                        <th>Numer Telefonu</th>
                        <th>Data Wizyty</th>
                        <th>Godzina Wizyty</th>
                        <th>Cena</th>
                        <th>Notatka</th>
                        <th>Akcje</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($visits as $nr=>$visit):?>
                    <tr>
                        <th scope="row"><?php echo $nr+1;?></th>
                        <td><?php echo $visit->getFirstname();?></td>
                        <td><?php echo $visit->getLastname();?></td>
                        <td><?php echo $visit->getPhone();?></td>
                        <td><?php echo $visit->getVdate();?></td>
                        <td><?php echo $visit->getVtime();?></td>
                        <td><?php echo $visit->getPrice();?></td>
                        <td><?php echo $visit->getNote();?></td>
                        <td>
                            <a href="?action=edit_visit&id=<?php echo $visit->getId();?>" data-toggle="tooltip" title="Edytuj" data-placement="left">
                                <button type="button" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </button>
                            </a>
                            <a href="?action=delete_visit&id=<?php echo $visit->getId();?>" data-toggle="toolip" title="Usuń" data-placement="right">
                                <button type="button" class="btn btn-danger">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </a>
                        </td>
                    </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
        </div>
    </div>
</div>
<?php include_once('elements/footer.phtml');?>