<?php
$visits_model = $this->getModel('visits');
$visits = $visits_model->getAll();
?>
<?php include_once ('elements/header.phtml');?>
<div class="container-fluid">
    <div class="row content">
        <?php include_once('elements/menu.phtml');?>
        <div class="col-sm-10">
            <h1>
                <small><?php echo $this->getPageLabel() . '(' . count($visits) . ')';?></small>
            </h1>
            <div class="up-button">
                <a href="?action=add_visit" data-toggle="tooltip" title="Dodaj Wizytę" data-placement="left">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>
                </a>
            </div>
            <hr>
            <div ng-app="visitApp" ng-controller="visitController">
                <div class="form-group">
                    <div class="col-sm-2">
                        <input type="text" class="form-control" ng-model="searchFirstname" placeholder="Szukaj imię...">
                    </div>
                    <div class="col-sm-2">
                        <input type="text" class="form-control" ng-model="searchLastname" placeholder="Szukaj nazwisko...">
                    </div>
                    <div class="col-sm-2">
                        <input type="text" class="form-control" ng-model="searchPhone" placeholder="Szukaj numer telefonu...">
                    </div>
                </div>
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th ng-click="orderByMe('firstname')" title="Sortuj imię">Imie</th>
                            <th ng-click="orderByMe('lastname')" title="Sortuj nazwisko">Nazwisko</th>
                            <th ng-click="orderByMe('phone')" title="Sortuj numer telefonu">Numer Telefonu</th>
                            <th ng-click="orderByMe('vdate')" title="Sortuj data">Data Wizyty</th>
                            <th ng-click="orderByMe('vtime')" title="Sortuj godzina">Godzina Wizyty</th>
                            <th>Cena</th>
                            <th>Notatka</th>
                            <th>Akcje</th>
                        </tr>
                    </thead>
                    <tbody>  
                        <tr ng-repeat = "x in visit_list | filter: {firstname: searchFirstname, lastname: searchLastname, phone: searchPhone} | orderBy: visitOrderBy">
                            <th>{{$index+1}}</th>
                            <td>{{x.firstname}}</td>
                            <td>{{x.lastname}}</td>
                            <td>{{x.phone}}</td>
                            <td>{{x.vdate}}</td>
                            <td>{{x.vtime}}</td>
                            <td>{{x.price}}</td>
                            <td>{{x.note}}</td>
                            <td>
                            <a href="?action=edit_visit&id={{x.id}}" data-toggle="tooltip" title="Edytuj" data-placement="left">
                                <button type="button" class="btn btn-primary">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </button>
                            </a>
                            <a href="?action=delete_visit&id={{x.id}}" data-toggle="toolip" title="Usuń" data-placement="right">
                                <button type="button" class="btn btn-danger">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </a>
                        </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <script>
                var app = angular.module("visitApp", []);
                app.controller("visitController", function($scope){
                    $scope.visit_list = <?php echo json_encode($visits);?>;
                    $scope.orderByMe = function(x){
                        $scope.visitOrderBy = x;
                    }
                }); 
            </script>
        </div>
    </div>
</div>
<?php include_once('elements/footer.phtml');?>