<!DOCTYPE html>
<html lang="en">
<head>
    <title>Piwnica Fryzur</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <!-- <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script> -->
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.0/angular.min.js"></script>
    <script>
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
    <style>
        @media (min-width:960px) {
            .up_button{
                position: absolute;
                right: 15px;
                top: 30px;
            }
        }
        .float-right {
            float: right;
        }
        .row.content {
            height: 888px
        }
        .sidenav {
            background-color: #f1f1f1;
            height: 100%;
        }
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }

        .closebtn {
            margin-left: 15px;
            color: black;
            font-weight: bold;
            float: right;
            font-size: 22px;
            line-height: 20px;
            cursor: pointer;
            transition: 0.3s;
        }

        .closebtn:hover {
            color: white;
        }

        .success {
            position:absolute;
            background-color: #ddffdd;
            border-left: 6px solid #4CAF50;
            padding: 20px;
            z-index: 100;
            width: 98%;
        }

    </style>
</head>

<body>

<?php if(isset($_SESSION['success'])) :?>
    <div class="col-sm-2">
    </div>
    <div class="col-sm-10">
        <div class="success text-center">
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            <strong>Success!</strong> Contact saved
        </div>
    </div>

<?php endif;?>